# AFU Accelerator Configuration

AFU_ACCEL_NAME = "vortex_afu"

# UUID stored as a string to preserve 128-bit hex format
AFU_ACCEL_UUID = 0x35F9452B_25C2_434C_93D5_6F8C60DB361C
AFU_ACCEL_UUID_S = "35F9452B-25C2-434C-93D5-6F8C60DB361C"

# Image Commands
AFU_IMAGE_CMD_MEM_READ = 1
AFU_IMAGE_CMD_MEM_WRITE = 2
AFU_IMAGE_CMD_RUN = 3
AFU_IMAGE_CMD_DCR_WRITE = 4
AFU_IMAGE_CMD_MAX_VALUE = 4

# MMIO Registers
AFU_IMAGE_MMIO_CMD_TYPE = 10
AFU_IMAGE_MMIO_CMD_ARG0 = 12
AFU_IMAGE_MMIO_CMD_ARG1 = 14
AFU_IMAGE_MMIO_CMD_ARG2 = 16
AFU_IMAGE_MMIO_STATUS = 18
AFU_IMAGE_MMIO_SCOPE_READ = 20
AFU_IMAGE_MMIO_SCOPE_WRITE = 22
AFU_IMAGE_MMIO_DEV_CAPS = 24
AFU_IMAGE_MMIO_ISA_CAPS = 26

# Miscellaneous
AFU_IMAGE_POWER = 0
AFU_TOP_IFC = "ccip_std_afu_avalon_mm"